spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # 변경분만 반영
  h2:
    console:
      enabled: true
  flyway:
    enabled: true